name: Release Deployment

on:
  release:
    types:
      - released

jobs:
  test_zip_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Delete all dist
      run: npm run clean
    - name: Install dependencies
      run: npm run install:extension 
    - name: Build
      run: npm run build
    - name: Zip up release
      id: zip_up
      run: zip -r AlgoSigner.zip ./dist/*
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./AlgoSigner.zip
        asset_name: AlgoSigner.zip
        asset_content_type: application/zip