name: Deployment
on:
  release:
    types:
      - released
jobs:
  test_zip_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12.15'
    - name: Delete all dist
      run: npm run clean
    - name: Install testing dependencies
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      run: npm install 
    - name: Build
      run: npm run build
    - name: Run headful puppeteer tests
      uses: djp3/puppeteer-headful@master
      with:
        args: npm test
    - name: Zip up release
      id: zip_up
      run: zip -r AlgoSigner.zip ./dist/*
    - name: Upload
      uses: actions/upload-release-asset@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./AlgoSigner.zip
        asset_name: AlgoSigner.zip
        asset_content_type: application/zip